#!/usr/bin/env bash

log() {
    if [[ $dry == "1" ]]; then
        printf "\n[DRY_RUN]: $@ \n"
    else
        printf "$@ \n"
    fi
}
execute() {
    log "\n[EXECUTING]: $@ \n"    
    if [[ $dry == "1" ]]; then
        return
    fi
    "$@"
}

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"

    
while [[ $# > 0 ]]; do

    if [[ $1 == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

cd $script_dir
scripts=$(find ./runs -maxdepth 2 -mindepth 1 -executable -type f)
log "$script_dir -- $filter"
log "\n Running: $scripts \n"
    
for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        log "Filtering -- $script"
        continue
    fi

    execute ./$script
done

