#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

sudo apt install tmux

git clone --depth 1 https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm" 

echo "Moving tmux Config Files"
cp .tmux.conf "$HOME/.tmux.conf"
