#!/usr/bin/env bash

git clone git@github.com:abdielrumaldo/nvim.git $HOME/.config/nvim

# Used by telescope
brew install ripgrep
brew install fzf

# Used by conform
brew install deno
go install github.com/reteps/dockerfmt@latest
go install github.com/google/yamlfmt/cmd/yamlfmt@latest
npm install -g js-beautify
