#!/usr/bin/env bash

git clone git@github.com:neovim/neovim.git $HOME/personal/neovim
cd $HOME/personal/neovim

git fetch
git checkout v0.10.4

sudo apt install build-essential
sudo apt install cmake gettext lua5.1 liblua5.1-0-dev
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
