#!/usr/bin/env bash

brew install zsh &>/dev/null


if [ -f ~/bin/zsh ]; then
   "~/bin/zsh -l"
fi  

# Sets theme
git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1\n
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

# DONT FORGET TO FETCH PLUGINS USING Ctrl + b and then Shift + i
