#!/usr/bin/env dash

# Date
date=$(date "+%a %F %R")

# Alsa master volume
volume=$(amixer get Master | grep "Mono" | tail -1 | awk '{print $4}' | tr -d '\[\]')
volume_state=$(amixer get Master | grep "Mono" | tail -1 | awk '{print $NF}')

# Battery
battery=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | awk '{print $NF}') # Status bar
battery_rate=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'energy-rate' | awk '{print $(NF-1)}')
battery_state=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | awk '{print $NF}')
battery_message=""

if [ "$battery_state" = "charging" ]; then
   battery_message="$battery_state @ $battery_rate W"
fi

# Wifi
wireless_status=$(nmcli | grep wlo | head -1 | awk -v FS=": " '{print $2}')

echo "Wifi:" $wireless_status " | " "Vol:" [$volume] $volume_state " | Pow:" [$battery] $battery_message "|" [$date] 
