#!/usr/bin/env bash
#
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/.config/ ~/personal ~/Documents/ ~/Downloads ~/personal/repos -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

# tr replaces any charcters given and input into an output
selected_name=$(basename "$selected" | tr ";:,." "____")

switch_to() {
    # if were not in tmux, put me in coach
    if [[ -z $TMUX ]]; then
        tmux attach-session -t $selected_name
    else
        tmux switch-client -t $selected_name
    fi
}

# If it exists, attach
if tmux has-session -t=$selected_name 2> /dev/null; then
    switch_to
    exit 0
fi

# If it doesn', create
tmux new-session -ds $selected_name -c $selected
switch_to

tmux send-keys -t $selected_name "ready-tmux" ^M


